// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.2
// source: caddycfginjector.proto

package caddycfginjector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Handle_Handler int32

const (
	Handle_ReverseProxy Handle_Handler = 0
)

// Enum value maps for Handle_Handler.
var (
	Handle_Handler_name = map[int32]string{
		0: "ReverseProxy",
	}
	Handle_Handler_value = map[string]int32{
		"ReverseProxy": 0,
	}
)

func (x Handle_Handler) Enum() *Handle_Handler {
	p := new(Handle_Handler)
	*p = x
	return p
}

func (x Handle_Handler) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Handle_Handler) Descriptor() protoreflect.EnumDescriptor {
	return file_caddycfginjector_proto_enumTypes[0].Descriptor()
}

func (Handle_Handler) Type() protoreflect.EnumType {
	return &file_caddycfginjector_proto_enumTypes[0]
}

func (x Handle_Handler) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Handle_Handler.Descriptor instead.
func (Handle_Handler) EnumDescriptor() ([]byte, []int) {
	return file_caddycfginjector_proto_rawDescGZIP(), []int{2, 0}
}

type Transport_Protocol int32

const (
	Transport_HTTP    Transport_Protocol = 0
	Transport_FastCGI Transport_Protocol = 1
)

// Enum value maps for Transport_Protocol.
var (
	Transport_Protocol_name = map[int32]string{
		0: "HTTP",
		1: "FastCGI",
	}
	Transport_Protocol_value = map[string]int32{
		"HTTP":    0,
		"FastCGI": 1,
	}
)

func (x Transport_Protocol) Enum() *Transport_Protocol {
	p := new(Transport_Protocol)
	*p = x
	return p
}

func (x Transport_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transport_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_caddycfginjector_proto_enumTypes[1].Descriptor()
}

func (Transport_Protocol) Type() protoreflect.EnumType {
	return &file_caddycfginjector_proto_enumTypes[1]
}

func (x Transport_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transport_Protocol.Descriptor instead.
func (Transport_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_caddycfginjector_proto_rawDescGZIP(), []int{3, 0}
}

type AddRouteReply_ReplyResult int32

const (
	AddRouteReply_ok    AddRouteReply_ReplyResult = 0
	AddRouteReply_error AddRouteReply_ReplyResult = 1
)

// Enum value maps for AddRouteReply_ReplyResult.
var (
	AddRouteReply_ReplyResult_name = map[int32]string{
		0: "ok",
		1: "error",
	}
	AddRouteReply_ReplyResult_value = map[string]int32{
		"ok":    0,
		"error": 1,
	}
)

func (x AddRouteReply_ReplyResult) Enum() *AddRouteReply_ReplyResult {
	p := new(AddRouteReply_ReplyResult)
	*p = x
	return p
}

func (x AddRouteReply_ReplyResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddRouteReply_ReplyResult) Descriptor() protoreflect.EnumDescriptor {
	return file_caddycfginjector_proto_enumTypes[2].Descriptor()
}

func (AddRouteReply_ReplyResult) Type() protoreflect.EnumType {
	return &file_caddycfginjector_proto_enumTypes[2]
}

func (x AddRouteReply_ReplyResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddRouteReply_ReplyResult.Descriptor instead.
func (AddRouteReply_ReplyResult) EnumDescriptor() ([]byte, []int) {
	return file_caddycfginjector_proto_rawDescGZIP(), []int{7, 0}
}

type AddRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Route *Route `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
}

func (x *AddRouteRequest) Reset() {
	*x = AddRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caddycfginjector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRouteRequest) ProtoMessage() {}

func (x *AddRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_caddycfginjector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRouteRequest.ProtoReflect.Descriptor instead.
func (*AddRouteRequest) Descriptor() ([]byte, []int) {
	return file_caddycfginjector_proto_rawDescGZIP(), []int{0}
}

func (x *AddRouteRequest) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Handles []*Handle `protobuf:"bytes,2,rep,name=handles,proto3" json:"handles,omitempty"`
	Matches []*Match  `protobuf:"bytes,3,rep,name=matches,proto3" json:"matches,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caddycfginjector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_caddycfginjector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_caddycfginjector_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Route) GetHandles() []*Handle {
	if x != nil {
		return x.Handles
	}
	return nil
}

func (x *Route) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type Handle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Handler   Handle_Handler `protobuf:"varint,1,opt,name=handler,proto3,enum=caddycfginjector.Handle_Handler" json:"handler,omitempty"`
	Transport *Transport     `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	Upstreams []*Upstream    `protobuf:"bytes,3,rep,name=upstreams,proto3" json:"upstreams,omitempty"`
}

func (x *Handle) Reset() {
	*x = Handle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caddycfginjector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Handle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handle) ProtoMessage() {}

func (x *Handle) ProtoReflect() protoreflect.Message {
	mi := &file_caddycfginjector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handle.ProtoReflect.Descriptor instead.
func (*Handle) Descriptor() ([]byte, []int) {
	return file_caddycfginjector_proto_rawDescGZIP(), []int{2}
}

func (x *Handle) GetHandler() Handle_Handler {
	if x != nil {
		return x.Handler
	}
	return Handle_ReverseProxy
}

func (x *Handle) GetTransport() *Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *Handle) GetUpstreams() []*Upstream {
	if x != nil {
		return x.Upstreams
	}
	return nil
}

type Transport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// https://caddyserver.com/docs/json/apps/http/servers/routes/handle/reverse_proxy/transport/
	Protocol Transport_Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=caddycfginjector.Transport_Protocol" json:"protocol,omitempty"`
}

func (x *Transport) Reset() {
	*x = Transport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caddycfginjector_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_caddycfginjector_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_caddycfginjector_proto_rawDescGZIP(), []int{3}
}

func (x *Transport) GetProtocol() Transport_Protocol {
	if x != nil {
		return x.Protocol
	}
	return Transport_HTTP
}

type Upstream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dial *Dial `protobuf:"bytes,1,opt,name=dial,proto3" json:"dial,omitempty"`
}

func (x *Upstream) Reset() {
	*x = Upstream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caddycfginjector_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Upstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upstream) ProtoMessage() {}

func (x *Upstream) ProtoReflect() protoreflect.Message {
	mi := &file_caddycfginjector_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upstream.ProtoReflect.Descriptor instead.
func (*Upstream) Descriptor() ([]byte, []int) {
	return file_caddycfginjector_proto_rawDescGZIP(), []int{4}
}

func (x *Upstream) GetDial() *Dial {
	if x != nil {
		return x.Dial
	}
	return nil
}

type Dial struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Dial) Reset() {
	*x = Dial{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caddycfginjector_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dial) ProtoMessage() {}

func (x *Dial) ProtoReflect() protoreflect.Message {
	mi := &file_caddycfginjector_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dial.ProtoReflect.Descriptor instead.
func (*Dial) Descriptor() ([]byte, []int) {
	return file_caddycfginjector_proto_rawDescGZIP(), []int{5}
}

func (x *Dial) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Dial) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Match struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosts []string `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Paths []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *Match) Reset() {
	*x = Match{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caddycfginjector_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_caddycfginjector_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_caddycfginjector_proto_rawDescGZIP(), []int{6}
}

func (x *Match) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *Match) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type AddRouteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  AddRouteReply_ReplyResult `protobuf:"varint,1,opt,name=result,proto3,enum=caddycfginjector.AddRouteReply_ReplyResult" json:"result,omitempty"`
	Message string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddRouteReply) Reset() {
	*x = AddRouteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caddycfginjector_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRouteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRouteReply) ProtoMessage() {}

func (x *AddRouteReply) ProtoReflect() protoreflect.Message {
	mi := &file_caddycfginjector_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRouteReply.ProtoReflect.Descriptor instead.
func (*AddRouteReply) Descriptor() ([]byte, []int) {
	return file_caddycfginjector_proto_rawDescGZIP(), []int{7}
}

func (x *AddRouteReply) GetResult() AddRouteReply_ReplyResult {
	if x != nil {
		return x.Result
	}
	return AddRouteReply_ok
}

func (x *AddRouteReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_caddycfginjector_proto protoreflect.FileDescriptor

var file_caddycfginjector_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x61, 0x64, 0x64, 0x79, 0x63, 0x66, 0x67, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x63, 0x61, 0x64, 0x64, 0x79, 0x63,
	0x66, 0x67, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x40, 0x0a, 0x0f, 0x41, 0x64,
	0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a,
	0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63,
	0x61, 0x64, 0x64, 0x79, 0x63, 0x66, 0x67, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x7e, 0x0a, 0x05,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x61, 0x64, 0x64, 0x79, 0x63, 0x66,
	0x67, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x52, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x07, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x61, 0x64,
	0x64, 0x79, 0x63, 0x66, 0x67, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x22, 0xd6, 0x01, 0x0a,
	0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x63, 0x61, 0x64, 0x64, 0x79,
	0x63, 0x66, 0x67, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x07, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x61, 0x64, 0x64, 0x79, 0x63, 0x66,
	0x67, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x38,
	0x0a, 0x09, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x61, 0x64, 0x64, 0x79, 0x63, 0x66, 0x67, 0x69, 0x6e, 0x6a, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x09, 0x75,
	0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x22, 0x1b, 0x0a, 0x07, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x50, 0x72,
	0x6f, 0x78, 0x79, 0x10, 0x00, 0x22, 0x70, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x63, 0x61, 0x64, 0x64, 0x79, 0x63, 0x66, 0x67, 0x69,
	0x6e, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x21, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x08, 0x0a, 0x04, 0x48, 0x54, 0x54, 0x50, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x61,
	0x73, 0x74, 0x43, 0x47, 0x49, 0x10, 0x01, 0x22, 0x36, 0x0a, 0x08, 0x55, 0x70, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x64, 0x64, 0x79, 0x63, 0x66, 0x67, 0x69, 0x6e, 0x6a, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x52, 0x04, 0x64, 0x69, 0x61, 0x6c, 0x22,
	0x2e, 0x0a, 0x04, 0x44, 0x69, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22,
	0x33, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x61, 0x74, 0x68, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x43, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x63, 0x61, 0x64, 0x64, 0x79, 0x63, 0x66,
	0x67, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x06, 0x0a, 0x02, 0x6f, 0x6b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x32, 0x64, 0x0a, 0x10, 0x43, 0x61, 0x64, 0x64, 0x79,
	0x43, 0x66, 0x67, 0x49, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x50, 0x0a, 0x08, 0x41,
	0x64, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x63, 0x61, 0x64, 0x64, 0x79, 0x63,
	0x66, 0x67, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x61, 0x64,
	0x64, 0x79, 0x63, 0x66, 0x67, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x64,
	0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x40, 0x5a,
	0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x6e, 0x67,
	0x38, 0x66, 0x69, 0x73, 0x68, 0x65, 0x72, 0x2f, 0x63, 0x61, 0x64, 0x64, 0x79, 0x63, 0x66, 0x67,
	0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x61, 0x64, 0x64, 0x79, 0x63, 0x66, 0x67, 0x69, 0x6e, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_caddycfginjector_proto_rawDescOnce sync.Once
	file_caddycfginjector_proto_rawDescData = file_caddycfginjector_proto_rawDesc
)

func file_caddycfginjector_proto_rawDescGZIP() []byte {
	file_caddycfginjector_proto_rawDescOnce.Do(func() {
		file_caddycfginjector_proto_rawDescData = protoimpl.X.CompressGZIP(file_caddycfginjector_proto_rawDescData)
	})
	return file_caddycfginjector_proto_rawDescData
}

var file_caddycfginjector_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_caddycfginjector_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_caddycfginjector_proto_goTypes = []interface{}{
	(Handle_Handler)(0),            // 0: caddycfginjector.Handle.Handler
	(Transport_Protocol)(0),        // 1: caddycfginjector.Transport.Protocol
	(AddRouteReply_ReplyResult)(0), // 2: caddycfginjector.AddRouteReply.ReplyResult
	(*AddRouteRequest)(nil),        // 3: caddycfginjector.AddRouteRequest
	(*Route)(nil),                  // 4: caddycfginjector.Route
	(*Handle)(nil),                 // 5: caddycfginjector.Handle
	(*Transport)(nil),              // 6: caddycfginjector.Transport
	(*Upstream)(nil),               // 7: caddycfginjector.Upstream
	(*Dial)(nil),                   // 8: caddycfginjector.Dial
	(*Match)(nil),                  // 9: caddycfginjector.Match
	(*AddRouteReply)(nil),          // 10: caddycfginjector.AddRouteReply
}
var file_caddycfginjector_proto_depIdxs = []int32{
	4,  // 0: caddycfginjector.AddRouteRequest.route:type_name -> caddycfginjector.Route
	5,  // 1: caddycfginjector.Route.handles:type_name -> caddycfginjector.Handle
	9,  // 2: caddycfginjector.Route.matches:type_name -> caddycfginjector.Match
	0,  // 3: caddycfginjector.Handle.handler:type_name -> caddycfginjector.Handle.Handler
	6,  // 4: caddycfginjector.Handle.transport:type_name -> caddycfginjector.Transport
	7,  // 5: caddycfginjector.Handle.upstreams:type_name -> caddycfginjector.Upstream
	1,  // 6: caddycfginjector.Transport.protocol:type_name -> caddycfginjector.Transport.Protocol
	8,  // 7: caddycfginjector.Upstream.dial:type_name -> caddycfginjector.Dial
	2,  // 8: caddycfginjector.AddRouteReply.result:type_name -> caddycfginjector.AddRouteReply.ReplyResult
	3,  // 9: caddycfginjector.CaddyCfgInjector.AddRoute:input_type -> caddycfginjector.AddRouteRequest
	10, // 10: caddycfginjector.CaddyCfgInjector.AddRoute:output_type -> caddycfginjector.AddRouteReply
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_caddycfginjector_proto_init() }
func file_caddycfginjector_proto_init() {
	if File_caddycfginjector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_caddycfginjector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_caddycfginjector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_caddycfginjector_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Handle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_caddycfginjector_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_caddycfginjector_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Upstream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_caddycfginjector_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dial); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_caddycfginjector_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Match); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_caddycfginjector_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRouteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_caddycfginjector_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_caddycfginjector_proto_goTypes,
		DependencyIndexes: file_caddycfginjector_proto_depIdxs,
		EnumInfos:         file_caddycfginjector_proto_enumTypes,
		MessageInfos:      file_caddycfginjector_proto_msgTypes,
	}.Build()
	File_caddycfginjector_proto = out.File
	file_caddycfginjector_proto_rawDesc = nil
	file_caddycfginjector_proto_goTypes = nil
	file_caddycfginjector_proto_depIdxs = nil
}
