// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.2
// source: caddycfginjector.proto

package caddycfginjector

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CaddyCfgInjectorClient is the client API for CaddyCfgInjector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CaddyCfgInjectorClient interface {
	AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc.CallOption) (*AddRouteReply, error)
}

type caddyCfgInjectorClient struct {
	cc grpc.ClientConnInterface
}

func NewCaddyCfgInjectorClient(cc grpc.ClientConnInterface) CaddyCfgInjectorClient {
	return &caddyCfgInjectorClient{cc}
}

func (c *caddyCfgInjectorClient) AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc.CallOption) (*AddRouteReply, error) {
	out := new(AddRouteReply)
	err := c.cc.Invoke(ctx, "/caddycfginjector.CaddyCfgInjector/AddRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaddyCfgInjectorServer is the server API for CaddyCfgInjector service.
// All implementations must embed UnimplementedCaddyCfgInjectorServer
// for forward compatibility
type CaddyCfgInjectorServer interface {
	AddRoute(context.Context, *AddRouteRequest) (*AddRouteReply, error)
	mustEmbedUnimplementedCaddyCfgInjectorServer()
}

// UnimplementedCaddyCfgInjectorServer must be embedded to have forward compatible implementations.
type UnimplementedCaddyCfgInjectorServer struct {
}

func (UnimplementedCaddyCfgInjectorServer) AddRoute(context.Context, *AddRouteRequest) (*AddRouteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRoute not implemented")
}
func (UnimplementedCaddyCfgInjectorServer) mustEmbedUnimplementedCaddyCfgInjectorServer() {}

// UnsafeCaddyCfgInjectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaddyCfgInjectorServer will
// result in compilation errors.
type UnsafeCaddyCfgInjectorServer interface {
	mustEmbedUnimplementedCaddyCfgInjectorServer()
}

func RegisterCaddyCfgInjectorServer(s grpc.ServiceRegistrar, srv CaddyCfgInjectorServer) {
	s.RegisterService(&CaddyCfgInjector_ServiceDesc, srv)
}

func _CaddyCfgInjector_AddRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaddyCfgInjectorServer).AddRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/caddycfginjector.CaddyCfgInjector/AddRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaddyCfgInjectorServer).AddRoute(ctx, req.(*AddRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CaddyCfgInjector_ServiceDesc is the grpc.ServiceDesc for CaddyCfgInjector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaddyCfgInjector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "caddycfginjector.CaddyCfgInjector",
	HandlerType: (*CaddyCfgInjectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRoute",
			Handler:    _CaddyCfgInjector_AddRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "caddycfginjector.proto",
}
